//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessKiller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessKiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream alert {
            get {
                return ResourceManager.GetStream("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (01/24/2017).
        /// </summary>
        internal static string Application_PublishDate {
            get {
                return ResourceManager.GetString("Application_PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://bbs.duowan.com/thread-45386278-1-1.html.
        /// </summary>
        internal static string Application_Web_HomePage {
            get {
                return ResourceManager.GetString("Application_Web_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小猪多开器.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到龙之谷主程序路径[DragonNest.exe], 请在设置中手动添加主程序路径.
        /// </summary>
        internal static string DNExe_NotFound_Message {
            get {
                return ResourceManager.GetString("DNExe_NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器未选择，请在设置中选择大区.
        /// </summary>
        internal static string DNServer_NotFound_Message {
            get {
                return ResourceManager.GetString("DNServer_NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DragonNest.
        /// </summary>
        internal static string DragonNest_Exe_Name {
            get {
                return ResourceManager.GetString("DragonNest_Exe_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnlauncher.
        /// </summary>
        internal static string DragonNest_LauncherExe_Name {
            get {
                return ResourceManager.GetString("DragonNest_LauncherExe_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\WOW6432Node\shandagames\DragonNest.
        /// </summary>
        internal static string DragonNest_Registry_Path {
            get {
                return ResourceManager.GetString("DragonNest_Registry_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] handle {
            get {
                object obj = ResourceManager.GetObject("handle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在关闭此进程....
        /// </summary>
        internal static string MainForm_button_click_KillingProcessMessage {
            get {
                return ResourceManager.GetString("MainForm_button_click_KillingProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现新版本:.
        /// </summary>
        internal static string MainForm_GetNewVersionDownloadLinkLabel_NewVersionFound_Message {
            get {
                return ResourceManager.GetString("MainForm_GetNewVersionDownloadLinkLabel_NewVersionFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击前往下载页.
        /// </summary>
        internal static string MainForm_GetNewVersionDownloadLinkLabel_NewVersionFound_Message_End {
            get {
                return ResourceManager.GetString("MainForm_GetNewVersionDownloadLinkLabel_NewVersionFound_Message_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前窗口.
        /// </summary>
        internal static string MainForm_GetProcessButton_ProcessButtonHighlightedTitle {
            get {
                return ResourceManager.GetString("MainForm_GetProcessButton_ProcessButtonHighlightedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点我切换至该窗口.
        /// </summary>
        internal static string MainForm_GetProcessButton_ProcessButtonTitle {
            get {
                return ResourceManager.GetString("MainForm_GetProcessButton_ProcessButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string MainForm_GetSettingsButton_SettingsButtonTitle {
            get {
                return ResourceManager.GetString("MainForm_GetSettingsButton_SettingsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动游戏.
        /// </summary>
        internal static string MainForm_GetStartGameButton_title {
            get {
                return ResourceManager.GetString("MainForm_GetStartGameButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有问题或者有疑问的加群来问吧，群号: 610614351.
        /// </summary>
        internal static string MainForm_HelpButton_Message {
            get {
                return ResourceManager.GetString("MainForm_HelpButton_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点我或按键掉线.
        /// </summary>
        internal static string MainForm_InitializeButtons_ClickToKillProcessHighlightedMessage {
            get {
                return ResourceManager.GetString("MainForm_InitializeButtons_ClickToKillProcessHighlightedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点我掉线.
        /// </summary>
        internal static string MainForm_InitializeButtons_ClickToKillProcessMessage {
            get {
                return ResourceManager.GetString("MainForm_InitializeButtons_ClickToKillProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 南方电信一区 柒才 &lt;女神之瞳&gt;.
        /// </summary>
        internal static string MainForm_InitializeCopyRightLabel_CopyrightMessage {
            get {
                return ResourceManager.GetString("MainForm_InitializeCopyRightLabel_CopyrightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本:.
        /// </summary>
        internal static string MainForm_InitializeVersionLabel_Version {
            get {
                return ResourceManager.GetString("MainForm_InitializeVersionLabel_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果需要多开，请等游戏完全启动或登陆后再点击启动游戏按钮.
        /// </summary>
        internal static string MainForm_start_game_button_first_click_message {
            get {
                return ResourceManager.GetString("MainForm_start_game_button_first_click_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏启动中....
        /// </summary>
        internal static string MainForm_start_game_button_game_start_message {
            get {
                return ResourceManager.GetString("MainForm_start_game_button_game_start_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请右键以管理员身份打开此程序.
        /// </summary>
        internal static string Program_ShowAdminErrorDialogBox_AdminPrivilegeMessage {
            get {
                return ResourceManager.GetString("Program_ShowAdminErrorDialogBox_AdminPrivilegeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 116.211.8.173;116.211.4.101 14301;14301 南方电信一区
        ///116.211.2.168;116.211.2.170 14301;14301 南方电信二区
        ///115.238.22.57;115.238.27.21 14301;14301 华东电信一区
        ///115.238.22.10;115.238.27.76 14301;14301 华东电信二区
        ///115.238.27.95;115.238.22.201 14301;14301 华东电信七区
        ///14.152.76.110;14.152.76.94 14301;14301 华南电信一区
        ///14.152.76.111;14.152.76.95 14301;14301 华南电信三区
        ///116.211.2.199;116.211.4.14 14301;14301 华中电信一区
        ///116.211.2.181;116.211.2.183 14301;14301 西南电信一区
        ///111.161.33.30;111.161.33.31 14301;14301 华北网通一区
        ///111.161.33.10;111.161.33.12 14301; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string servers {
            get {
                return ResourceManager.GetString("servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用秒掉功能会增加封号风险，请慎重使用，如果被反外挂发现，请立即停止使用.
        /// </summary>
        internal static string SettingsForm_DisableProcessKillCheckBox_CheckedChanged_Warnning {
            get {
                return ResourceManager.GetString("SettingsForm_DisableProcessKillCheckBox_CheckedChanged_Warnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间设置必须大于0.
        /// </summary>
        internal static string SettingsForm_InvalidField_CountDownTime {
            get {
                return ResourceManager.GetString("SettingsForm_InvalidField_CountDownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 想啥呢？提示时间必须小于倒计时时间 (mdzz).
        /// </summary>
        internal static string SettingsForm_InvalidField_CountDownWarnningTime {
            get {
                return ResourceManager.GetString("SettingsForm_InvalidField_CountDownWarnningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择龙之谷游戏文件夹(包含游戏启动程序的根目录).
        /// </summary>
        internal static string SettingsForm_PathSelection_Description {
            get {
                return ResourceManager.GetString("SettingsForm_PathSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未在该目录下发现龙之谷启动程序，请选择含有龙之谷启动程序的游戏目录.
        /// </summary>
        internal static string SettingsForm_PathSelection_InvalidPath_Message {
            get {
                return ResourceManager.GetString("SettingsForm_PathSelection_InvalidPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers.
        /// </summary>
        internal static string WINNT_AppCompatFlags_Registry_Path {
            get {
                return ResourceManager.GetString("WINNT_AppCompatFlags_Registry_Path", resourceCulture);
            }
        }
    }
}
